function [] = make_disdel()
load('FINAL_DISDEL.mat');

% Create DisDel netcdf file with 10min, hourly, and daily data.

% First construct the name of the netcdf file.
if strcmp(inputs.mooring(1:2),'pa')
    location = 'PAPA';
    nomloc = '(nominally 50.1N, 144.9W)';
    lat = 50.1; lon = -144.9;
    lats = [50,50.2]; lons = [-145,-144.7];
    platcode = '4800400';
    array = 'STATION-P';
    area = 'North Pacific';
elseif strcmp(inputs.mooring(1:2),'ke')
    location = 'KEO';
    nomloc = '(nominally 32.3N, 144.6E)';
    lat = 32.3; lon = 144.6;
    lats = [32.1,32.65]; lons = [144.35,144.75];
    platcode = '2800401';
    array = 'KUROSHIO EXTENSION';
    area = 'Western Pacific Kuroshio Extension';
end

% Name of file.
ncid = sprintf('DisDel_%s_%s%s_D_DEEP-SEACAT-all.nc',location,inputs.startdt(1:4),upper(inputs.mooring));
delete(ncid);

% Move old file to keep out of the way.
% if ~isempty(dir(ncid))
%     if ~exist('OLD_NC','dir')
%         mkdir('OLD_NC');
%     end
%     movefile(ncid,'OLD_NC');
% end

% Create nc file and integrate coordinate variables (i.e. both dimensions and variables).
nccreate(ncid,'TIME','Dimensions',{'TIME',inf},'Format','classic')
ncwrite(ncid,'TIME',time-712224)
nccreate(ncid,'TIME_HR','Dimensions',{'TIME_HR',length(time_hr)},'Format','classic')
ncwrite(ncid,'TIME_HR',time_hr-712224)
nccreate(ncid,'TIME_DY','Dimensions',{'TIME_DY',length(time_dy)},'Format','classic')
ncwrite(ncid,'TIME_DY',time_dy-712224)
nccreate(ncid,'LATITUDE','Dimensions',{'LATITUDE',1},'Format','classic','DataType','single')
ncwrite(ncid,'LATITUDE',lat)
nccreate(ncid,'LONGITUDE','Dimensions',{'LONGITUDE',1},'Format','classic','DataType','single')
ncwrite(ncid,'LONGITUDE',lon)
nccreate(ncid,'DEPTH','Dimensions',{'DEPTH',1},'Format','classic','DataType','single')
ncwrite(ncid,'DEPTH',round(inputs.nominal_depths))

% 10 Minute
nccreate(ncid,'TEMP','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','classic','DataType','single')
ncwrite(ncid,'TEMP',reshape(dft.temp,1,1,1,size(time,1)))
nccreate(ncid,'TEMP_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','classic','DataType','int8')
ncwrite(ncid,'TEMP_QC',reshape(flags.T,1,1,1,size(time,1)))

nccreate(ncid,'PRES','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','classic','DataType','single')
ncwrite(ncid,'PRES',reshape(dft.pres,1,1,1,size(time,1)))
nccreate(ncid,'PRES_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','classic','DataType','int8')
ncwrite(ncid,'PRES_QC',reshape(flags.P,1,1,1,size(time,1)))

%nccreate(ncid,'CNDC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','classic','DataType','single')
%ncwrite(ncid,'CNDC',reshape(dft.cond,1,1,1,size(time,1)))
%nccreate(ncid,'CNDC_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','classic','DataType','int8')
%ncwrite(ncid,'CNDC_QC',reshape(flags.C,1,1,1,size(time,1)))

%nccreate(ncid,'DENS','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','classic','DataType','single')
%ncwrite(ncid,'DENS',reshape(dft.dens,1,1,1,size(time,1)))
%nccreate(ncid,'DENS_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','classic','DataType','int8')
%ncwrite(ncid,'DENS_QC',reshape(flags.D,1,1,1,size(time,1)))

%nccreate(ncid,'PSAL','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','classic','DataType','single')
%ncwrite(ncid,'PSAL',reshape(dft.sal,1,1,1,size(time,1)))
%nccreate(ncid,'PSAL_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','classic','DataType','int8')
%ncwrite(ncid,'PSAL_QC',reshape(flags.S,1,1,1,size(time,1)))


% Hourly
nccreate(ncid,'TEMP_HR','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_HR',size(time_hr,1)},'Format','classic','DataType','single')
ncwrite(ncid,'TEMP_HR',reshape(flt.temp,1,1,1,size(time_hr,1)))
nccreate(ncid,'TEMP_HR_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_HR',size(time_hr,1)},'Format','classic','DataType','int8')
ncwrite(ncid,'TEMP_HR_QC',reshape(flags.T_hr,1,1,1,size(time_hr,1)))

nccreate(ncid,'PRES_HR','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_HR',size(time_hr,1)},'Format','classic','DataType','single')
ncwrite(ncid,'PRES_HR',reshape(flt.pres,1,1,1,size(time_hr,1)))
nccreate(ncid,'PRES_HR_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_HR',size(time_hr,1)},'Format','classic','DataType','int8')
ncwrite(ncid,'PRES_HR_QC',reshape(flags.P_hr,1,1,1,size(time_hr,1)))

nccreate(ncid,'CNDC_HR','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_HR',size(time_hr,1)},'Format','classic','DataType','single')
ncwrite(ncid,'CNDC_HR',reshape(flt.cond,1,1,1,size(time_hr,1)))
nccreate(ncid,'CNDC_HR_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_HR',size(time_hr,1)},'Format','classic','DataType','int8')
ncwrite(ncid,'CNDC_HR_QC',reshape(flags.C_hr,1,1,1,size(time_hr,1)))

nccreate(ncid,'DENS_HR','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_HR',size(time_hr,1)},'Format','classic','DataType','single')
ncwrite(ncid,'DENS_HR',reshape(flt.dens,1,1,1,size(time_hr,1)))
nccreate(ncid,'DENS_HR_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_HR',size(time_hr,1)},'Format','classic','DataType','int8')
ncwrite(ncid,'DENS_HR_QC',reshape(flags.D_hr,1,1,1,size(time_hr,1)))

nccreate(ncid,'PSAL_HR','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_HR',size(time_hr,1)},'Format','classic','DataType','single')
ncwrite(ncid,'PSAL_HR',reshape(flt.sal,1,1,1,size(time_hr,1)))
nccreate(ncid,'PSAL_HR_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_HR',size(time_hr,1)},'Format','classic','DataType','int8')
ncwrite(ncid,'PSAL_HR_QC',reshape(flags.S_hr,1,1,1,size(time_hr,1)))

% Daily
nccreate(ncid,'TEMP_DY','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','classic','DataType','single')
ncwrite(ncid,'TEMP_DY',reshape(davg.temp,1,1,1,size(time_dy,1)))
nccreate(ncid,'TEMP_DY_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','classic','DataType','int8')
ncwrite(ncid,'TEMP_DY_QC',reshape(flags.T_dy,1,1,1,size(time_dy,1)))

nccreate(ncid,'PRES_DY','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','classic','DataType','single')
ncwrite(ncid,'PRES_DY',reshape(davg.pres,1,1,1,size(time_dy,1)))
nccreate(ncid,'PRES_DY_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','classic','DataType','int8')
ncwrite(ncid,'PRES_DY_QC',reshape(flags.P_dy,1,1,1,size(time_dy,1)))

nccreate(ncid,'CNDC_DY','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','classic','DataType','single')
ncwrite(ncid,'CNDC_DY',reshape(davg.cond,1,1,1,size(time_dy,1)))
nccreate(ncid,'CNDC_DY_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','classic','DataType','int8')
ncwrite(ncid,'CNDC_DY_QC',reshape(flags.C_dy,1,1,1,size(time_dy,1)))

nccreate(ncid,'DENS_DY','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','classic','DataType','single')
ncwrite(ncid,'DENS_DY',reshape(davg.dens,1,1,1,size(time_dy,1)))
nccreate(ncid,'DENS_DY_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','classic','DataType','int8')
ncwrite(ncid,'DENS_DY_QC',reshape(flags.D_dy,1,1,1,size(time_dy,1)))

nccreate(ncid,'PSAL_DY','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','classic','DataType','single')
ncwrite(ncid,'PSAL_DY',reshape(davg.sal,1,1,1,size(time_dy,1)))
nccreate(ncid,'PSAL_DY_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','classic','DataType','int8')
ncwrite(ncid,'PSAL_DY_QC',reshape(flags.S_dy,1,1,1,size(time_dy,1)))



% Add attributes to each variable
ncwriteatt(ncid,'TIME','long_name','time')
ncwriteatt(ncid,'TIME','standard_name','time')
ncwriteatt(ncid,'TIME','units','days since 1950-01-01T00:00:00Z')
ncwriteatt(ncid,'TIME','valid_min',time(1)-712224)
ncwriteatt(ncid,'TIME','valid_max',time(end)-712224)
ncwriteatt(ncid,'TIME','point_spacing','even')
ncwriteatt(ncid,'TIME','QC_indicator','Good data')
ncwriteatt(ncid,'TIME','Processing_level','Ranges applied, bad data flagged')
ncwriteatt(ncid,'TIME','Uncertainty','None')
ncwriteatt(ncid,'TIME','axis','T')

ncwriteatt(ncid,'TIME_HR','long_name','time')
ncwriteatt(ncid,'TIME_HR','standard_name','time')
ncwriteatt(ncid,'TIME_HR','units','days since 1950-01-01T00:00:00Z')
ncwriteatt(ncid,'TIME_HR','valid_min',time_hr(1)-712224)
ncwriteatt(ncid,'TIME_HR','valid_max',time_hr(end)-712224)
ncwriteatt(ncid,'TIME_HR','point_spacing','even')
ncwriteatt(ncid,'TIME_HR','QC_indicator','Good data')
ncwriteatt(ncid,'TIME_HR','Processing_level','Ranges applied, bad data flagged')
ncwriteatt(ncid,'TIME_HR','Uncertainty','None')
ncwriteatt(ncid,'TIME_HR','axis','T')

ncwriteatt(ncid,'TIME_DY','long_name','time')
ncwriteatt(ncid,'TIME_DY','standard_name','time')
ncwriteatt(ncid,'TIME_DY','units','days since 1950-01-01T00:00:00Z')
ncwriteatt(ncid,'TIME_DY','valid_min',time_dy(1)-712224)
ncwriteatt(ncid,'TIME_DY','valid_max',time_dy(end)-712224)
ncwriteatt(ncid,'TIME_DY','point_spacing','even')
ncwriteatt(ncid,'TIME_DY','QC_indicator','Good data')
ncwriteatt(ncid,'TIME_DY','Processing_level','Ranges applied, bad data flagged')
ncwriteatt(ncid,'TIME_DY','Uncertainty','None')
ncwriteatt(ncid,'TIME_DY','axis','T')

ncwriteatt(ncid,'LATITUDE','long_name','Anchor Latitude')
ncwriteatt(ncid,'LATITUDE','standard_name','latitude')
ncwriteatt(ncid,'LATITUDE','units','degrees_north')
ncwriteatt(ncid,'LATITUDE','valid_min',-90)
ncwriteatt(ncid,'LATITUDE','valid_max',90)
ncwriteatt(ncid,'LATITUDE','QC_indicator','nominal vlaue')
ncwriteatt(ncid,'LATITUDE','Processing_level','Data manually reviewed')
ncwriteatt(ncid,'LATITUDE','Uncertainty','None')
ncwriteatt(ncid,'LATITUDE','axis','Y')
ncwriteatt(ncid,'LATITUDE','reference','WGS84')
ncwriteatt(ncid,'LATITUDE','coordinate_reference_frame','urn:ogc:crs:EPSG::4326')

ncwriteatt(ncid,'LONGITUDE','long_name','Anchor Longitude')
ncwriteatt(ncid,'LONGITUDE','standard_name','longitude')
ncwriteatt(ncid,'LONGITUDE','units','degrees_east')
ncwriteatt(ncid,'LONGITUDE','valid_min',-180)
ncwriteatt(ncid,'LONGITUDE','valid_max',180)
ncwriteatt(ncid,'LONGITUDE','QC_indicator','nominal value')
ncwriteatt(ncid,'LONGITUDE','Processing_level','Data manually reviewed')
ncwriteatt(ncid,'LONGITUDE','Uncertainty','None')
ncwriteatt(ncid,'LONGITUDE','axis','X')
ncwriteatt(ncid,'LONGITUDE','reference','WGS84')
ncwriteatt(ncid,'LONGITUDE','coordinate_reference_frame','urn:ogc:crs:EPSG::4326')

ncwriteatt(ncid,'DEPTH','long_name','Depth of each measurement')
ncwriteatt(ncid,'DEPTH','standard_name','depth')
ncwriteatt(ncid,'DEPTH','units','meters')
ncwriteatt(ncid,'DEPTH','positive','down')
ncwriteatt(ncid,'DEPTH','valid_min',round(inputs.nominal_depths(1)))
ncwriteatt(ncid,'DEPTH','valid_max',round(inputs.nominal_depths(1)))
ncwriteatt(ncid,'DEPTH','QC_indicator','nominal value')
ncwriteatt(ncid,'DEPTH','Processing_level','Data manually reviewed')
ncwriteatt(ncid,'DEPTH','Uncertainty','Approximate value')
ncwriteatt(ncid,'DEPTH','axis','Z')
ncwriteatt(ncid,'DEPTH','reference','sea_level')
ncwriteatt(ncid,'DEPTH','coordinate_reference_frame','urn:ogc:crs:EPSG::5831')



% Write highres attributes.
ncwriteatt(ncid,'TEMP','long_name','sea water temperature in-situ ITS-90 scale')
ncwriteatt(ncid,'TEMP','standard_name','sea_water_temperature')
ncwriteatt(ncid,'TEMP','units','degree_Celsius')
ncwriteatt(ncid,'TEMP','valid_min',-2)
ncwriteatt(ncid,'TEMP','valid_max',40)
ncwriteatt(ncid,'TEMP','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid,'TEMP','QC_indicator','Good data')
ncwriteatt(ncid,'TEMP','Processing_level','Data manually reviewed')
ncwriteatt(ncid,'TEMP','ancillary_variables','TEMP_QC')
ncwriteatt(ncid,'TEMP','reference_scale','ITS-90')
ncwriteatt(ncid,'TEMP','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid,'TEMP','sensor_name','SBE37S')
ncwriteatt(ncid,'TEMP','sensor_serial_number',inputs.serial)

ncwriteatt(ncid,'TEMP_QC','long_name','quality flag')
ncwriteatt(ncid,'TEMP_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid,'TEMP_QC','valid_min',0)
ncwriteatt(ncid,'TEMP_QC','valid_max',5)
%ncwriteatt(ncid,'TEMP_QC','valid_max',9)
ncwriteatt(ncid,'TEMP_QC','flag_values',int8([0,1,2,3,4,5]))
%ncwriteatt(ncid,'TEMP_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
ncwriteatt(ncid,'TEMP_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
%ncwriteatt(ncid,'TEMP_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')

ncwriteatt(ncid,'PRES','long_name','sea water pressure')
ncwriteatt(ncid,'PRES','standard_name','sea_water_pressure')
ncwriteatt(ncid,'PRES','units','decibar')
ncwriteatt(ncid,'PRES','valid_min',0)
ncwriteatt(ncid,'PRES','valid_max',6000)
ncwriteatt(ncid,'PRES','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid,'PRES','QC_indicator','Good data')
ncwriteatt(ncid,'PRES','Processing_level','Data manually reviewed')
ncwriteatt(ncid,'PRES','ancillary_variables','PRES_QC')
ncwriteatt(ncid,'PRES','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid,'PRES','sensor_name','SBE37S')
ncwriteatt(ncid,'PRES','sensor_serial_number',inputs.serial_pressure)

ncwriteatt(ncid,'PRES_QC','long_name','quality flag')
ncwriteatt(ncid,'PRES_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid,'PRES_QC','valid_min',0)
ncwriteatt(ncid,'PRES_QC','valid_max',5)
%ncwriteatt(ncid,'PRES_QC','valid_max',9)
ncwriteatt(ncid,'PRES_QC','flag_values',int8([0,1,2,3,4,5]))
%ncwriteatt(ncid,'PRES_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
ncwriteatt(ncid,'PRES_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
%ncwriteatt(ncid,'PRES_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')



% Hourly
ncwriteatt(ncid,'TEMP_HR','long_name','sea water temperature in-situ ITS-90 scale')
ncwriteatt(ncid,'TEMP_HR','standard_name','sea_water_temperature')
ncwriteatt(ncid,'TEMP_HR','units','degree_Celsius')
ncwriteatt(ncid,'TEMP_HR','valid_min',-2)
ncwriteatt(ncid,'TEMP_HR','valid_max',40)
ncwriteatt(ncid,'TEMP_HR','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid,'TEMP_HR','QC_indicator','Good data')
ncwriteatt(ncid,'TEMP_HR','Processing_level','Data manually reviewed')
ncwriteatt(ncid,'TEMP_HR','ancillary_variables','TEMP_HR_QC')
ncwriteatt(ncid,'TEMP_HR','reference_scale','ITS-90')
ncwriteatt(ncid,'TEMP_HR','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid,'TEMP_HR','sensor_name','SBE37S')
ncwriteatt(ncid,'TEMP_HR','sensor_serial_number',inputs.serial)

ncwriteatt(ncid,'TEMP_HR_QC','long_name','quality flag')
ncwriteatt(ncid,'TEMP_HR_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid,'TEMP_HR_QC','valid_min',0)
ncwriteatt(ncid,'TEMP_HR_QC','valid_max',5)
%ncwriteatt(ncid,'TEMP_HR_QC','valid_max',9)
ncwriteatt(ncid,'TEMP_HR_QC','flag_values',int8([0,1,2,3,4,5]))
%ncwriteatt(ncid,'TEMP_HR_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
ncwriteatt(ncid,'TEMP_HR_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
%ncwriteatt(ncid,'TEMP_HR_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')

ncwriteatt(ncid,'PRES_HR','long_name','sea water pressure')
ncwriteatt(ncid,'PRES_HR','standard_name','sea_water_pressure')
ncwriteatt(ncid,'PRES_HR','units','decibar')
ncwriteatt(ncid,'PRES_HR','valid_min',0)
ncwriteatt(ncid,'PRES_HR','valid_max',6000)
ncwriteatt(ncid,'PRES_HR','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid,'PRES_HR','QC_indicator','Good data')
ncwriteatt(ncid,'PRES_HR','Processing_level','Data manually reviewed')
ncwriteatt(ncid,'PRES_HR','ancillary_variables','PRES_QC')
ncwriteatt(ncid,'PRES_HR','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid,'PRES_HR','sensor_name','SBE37S')
ncwriteatt(ncid,'PRES_HR','sensor_serial_number',inputs.serial_pressure)

ncwriteatt(ncid,'PRES_HR_QC','long_name','quality flag')
ncwriteatt(ncid,'PRES_HR_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid,'PRES_HR_QC','valid_min',0)
ncwriteatt(ncid,'PRES_HR_QC','valid_max',5)
%ncwriteatt(ncid,'PRES_HR_QC','valid_max',9)
ncwriteatt(ncid,'PRES_HR_QC','flag_values',int8([0,1,2,3,4,5]))
%ncwriteatt(ncid,'PRES_HR_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
ncwriteatt(ncid,'PRES_HR_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
%ncwriteatt(ncid,'PRES_HR_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')

ncwriteatt(ncid,'CNDC_HR','long_name','sea water conductivity')
ncwriteatt(ncid,'CNDC_HR','standard_name','sea_water_electrical_conductivity')
ncwriteatt(ncid,'CNDC_HR','units','S/m')
ncwriteatt(ncid,'CNDC_HR','valid_min',0)
ncwriteatt(ncid,'CNDC_HR','valid_max',7)
ncwriteatt(ncid,'CNDC_HR','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid,'CNDC_HR','QC_indicator','Good data')
ncwriteatt(ncid,'CNDC_HR','Processing_level','Data manually reviewed')
ncwriteatt(ncid,'CNDC_HR','ancillary_variables','CNDC_HR_QC')
ncwriteatt(ncid,'CNDC_HR','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid,'CNDC_HR','sensor_name','SBE37S')
ncwriteatt(ncid,'CNDC_HR','sensor_serial_number',inputs.serial)

ncwriteatt(ncid,'CNDC_HR_QC','long_name','quality flag')
ncwriteatt(ncid,'CNDC_HR_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid,'CNDC_HR_QC','valid_min',0)
ncwriteatt(ncid,'CNDC_HR_QC','valid_max',5)
%ncwriteatt(ncid,'CNDC_HR_QC','valid_max',9)
ncwriteatt(ncid,'CNDC_HR_QC','flag_values',int8([0,1,2,3,4,5]))
%ncwriteatt(ncid,'CNDC_HR_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
ncwriteatt(ncid,'CNDC_HR_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
%ncwriteatt(ncid,'CNDC_HR_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')

if strcmp(inputs.mooring(1:2),'pa')
    ncwriteatt(ncid,'DENS_HR','long_name','sigma-theta (potential density adjusted to 4000m)')
elseif strcmp(inputs.mooring(1:2),'ke')
    ncwriteatt(ncid,'DENS_HR','long_name','sigma-theta (potential density adjusted to 6000m)')
end
ncwriteatt(ncid,'DENS_HR','standard_name','sea_water_sigma_theta')
ncwriteatt(ncid,'DENS_HR','units','kg m-3')
ncwriteatt(ncid,'DENS_HR','valid_min',0)
ncwriteatt(ncid,'DENS_HR','valid_max',100)
ncwriteatt(ncid,'DENS_HR','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid,'DENS_HR','QC_indicator','Good data')
ncwriteatt(ncid,'DENS_HR','Processing_level','Data manually reviewed')
ncwriteatt(ncid,'DENS_HR','ancillary_variables','DENS_HR_QC')
ncwriteatt(ncid,'DENS_HR','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid,'DENS_HR','sensor_name','SBE37S')
ncwriteatt(ncid,'DENS_HR','sensor_serial_number',inputs.serial)
ncwriteatt(ncid,'DENS_HR','comment','Derived from measured conductivity, temperature, and pressure.')

ncwriteatt(ncid,'DENS_HR_QC','long_name','quality flag')
ncwriteatt(ncid,'DENS_HR_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid,'DENS_HR_QC','valid_min',0)
ncwriteatt(ncid,'DENS_HR_QC','valid_max',5)
%ncwriteatt(ncid,'DENS_HR_QC','valid_max',9)
ncwriteatt(ncid,'DENS_HR_QC','flag_values',int8([0,1,2,3,4,5]))
%ncwriteatt(ncid,'DENS_HR_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
ncwriteatt(ncid,'DENS_HR_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
%ncwriteatt(ncid,'DENS_HR_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')

ncwriteatt(ncid,'PSAL_HR','long_name','sea water salinity')
ncwriteatt(ncid,'PSAL_HR','standard_name','sea_water_practical_salinity')
ncwriteatt(ncid,'PSAL_HR','units','1')
ncwriteatt(ncid,'PSAL_HR','valid_min',25)
ncwriteatt(ncid,'PSAL_HR','valid_max',45)
ncwriteatt(ncid,'PSAL_HR','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid,'PSAL_HR','QC_indicator','Good data')
ncwriteatt(ncid,'PSAL_HR','Processing_level','Data manually reviewed')
ncwriteatt(ncid,'PSAL_HR','ancillary_variables','PSAL_HR_QC')
ncwriteatt(ncid,'PSAL_HR','reference_scale','PSS-78')
ncwriteatt(ncid,'PSAL_HR','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid,'PSAL_HR','sensor_name','SBE37S')
ncwriteatt(ncid,'PSAL_HR','sensor_serial_number',inputs.serial)
ncwriteatt(ncid,'PSAL_HR','comment','In PSU. Derived from measured conductivity, temperature, and pressure.')

ncwriteatt(ncid,'PSAL_HR_QC','long_name','quality flag')
ncwriteatt(ncid,'PSAL_HR_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid,'PSAL_HR_QC','valid_min',0)
ncwriteatt(ncid,'PSAL_HR_QC','valid_max',5)
%ncwriteatt(ncid,'PSAL_HR_QC','valid_max',9)
ncwriteatt(ncid,'PSAL_HR_QC','flag_values',int8([0,1,2,3,4,5]))
%ncwriteatt(ncid,'PSAL_HR_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
ncwriteatt(ncid,'PSAL_HR_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
%ncwriteatt(ncid,'PSAL_HR_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')



% Daily
ncwriteatt(ncid,'TEMP_DY','long_name','sea water temperature in-situ ITS-90 scale')
ncwriteatt(ncid,'TEMP_DY','standard_name','sea_water_temperature')
ncwriteatt(ncid,'TEMP_DY','units','degree_Celsius')
ncwriteatt(ncid,'TEMP_DY','valid_min',-2)
ncwriteatt(ncid,'TEMP_DY','valid_max',40)
ncwriteatt(ncid,'TEMP_DY','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid,'TEMP_DY','QC_indicator','Good data')
ncwriteatt(ncid,'TEMP_DY','Processing_level','Data manually reviewed')
ncwriteatt(ncid,'TEMP_DY','ancillary_variables','TEMP_DY_QC')
ncwriteatt(ncid,'TEMP_DY','reference_scale','ITS-90')
ncwriteatt(ncid,'TEMP_DY','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid,'TEMP_DY','sensor_name','SBE37S')
ncwriteatt(ncid,'TEMP_DY','sensor_serial_number',inputs.serial)

ncwriteatt(ncid,'TEMP_DY_QC','long_name','quality flag')
ncwriteatt(ncid,'TEMP_DY_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid,'TEMP_DY_QC','valid_min',0)
ncwriteatt(ncid,'TEMP_DY_QC','valid_max',5)
%ncwriteatt(ncid,'TEMP_DY_QC','valid_max',9)
ncwriteatt(ncid,'TEMP_DY_QC','flag_values',int8([0,1,2,3,4,5]))
%ncwriteatt(ncid,'TEMP_DY_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
ncwriteatt(ncid,'TEMP_DY_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
%ncwriteatt(ncid,'TEMP_DY_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')

ncwriteatt(ncid,'PRES_DY','long_name','sea water pressure')
ncwriteatt(ncid,'PRES_DY','standard_name','sea_water_pressure')
ncwriteatt(ncid,'PRES_DY','units','decibar')
ncwriteatt(ncid,'PRES_DY','valid_min',0)
ncwriteatt(ncid,'PRES_DY','valid_max',6000)
ncwriteatt(ncid,'PRES_DY','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid,'PRES_DY','QC_indicator','Good data')
ncwriteatt(ncid,'PRES_DY','Processing_level','Data manually reviewed')
ncwriteatt(ncid,'PRES_DY','ancillary_variables','PRES_QC')
ncwriteatt(ncid,'PRES_DY','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid,'PRES_DY','sensor_name','SBE37S')
ncwriteatt(ncid,'PRES_DY','sensor_serial_number',inputs.serial_pressure)

ncwriteatt(ncid,'PRES_DY_QC','long_name','quality flag')
ncwriteatt(ncid,'PRES_DY_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid,'PRES_DY_QC','valid_min',0)
ncwriteatt(ncid,'PRES_DY_QC','valid_max',5)
%ncwriteatt(ncid,'PRES_DY_QC','valid_max',9)
ncwriteatt(ncid,'PRES_DY_QC','flag_values',int8([0,1,2,3,4,5]))
%ncwriteatt(ncid,'PRES_DY_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
ncwriteatt(ncid,'PRES_DY_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
%ncwriteatt(ncid,'PRES_DY_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')

ncwriteatt(ncid,'CNDC_DY','long_name','sea water conductivity')
ncwriteatt(ncid,'CNDC_DY','standard_name','sea_water_electrical_conductivity')
ncwriteatt(ncid,'CNDC_DY','units','S/m')
ncwriteatt(ncid,'CNDC_DY','valid_min',0)
ncwriteatt(ncid,'CNDC_DY','valid_max',7)
ncwriteatt(ncid,'CNDC_DY','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid,'CNDC_DY','QC_indicator','Good data')
ncwriteatt(ncid,'CNDC_DY','Processing_level','Data manually reviewed')
ncwriteatt(ncid,'CNDC_DY','ancillary_variables','CNDC_DY_QC')
ncwriteatt(ncid,'CNDC_DY','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid,'CNDC_DY','sensor_name','SBE37S')
ncwriteatt(ncid,'CNDC_DY','sensor_serial_number',inputs.serial)

ncwriteatt(ncid,'CNDC_DY_QC','long_name','quality flag')
ncwriteatt(ncid,'CNDC_DY_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid,'CNDC_DY_QC','valid_min',0)
ncwriteatt(ncid,'CNDC_DY_QC','valid_max',5)
%ncwriteatt(ncid,'CNDC_DY_QC','valid_max',9)
ncwriteatt(ncid,'CNDC_DY_QC','flag_values',int8([0,1,2,3,4,5]))
%ncwriteatt(ncid,'CNDC_DY_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
ncwriteatt(ncid,'CNDC_DY_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
%ncwriteatt(ncid,'CNDC_DY_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')

if strcmp(inputs.mooring(1:2),'pa')
ncwriteatt(ncid,'DENS_DY','long_name','sigma-theta (potential density adjusted to 4000m)')
elseif strcmp(inputs.mooring(1:2),'ke')
ncwriteatt(ncid,'DENS_DY','long_name','sigma-theta (potential density adjusted to 6000m)')
end
ncwriteatt(ncid,'DENS_DY','standard_name','sea_water_sigma_theta')
ncwriteatt(ncid,'DENS_DY','units','kg m-3')
ncwriteatt(ncid,'DENS_DY','valid_min',0)
ncwriteatt(ncid,'DENS_DY','valid_max',100)
ncwriteatt(ncid,'DENS_DY','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid,'DENS_DY','QC_indicator','Good data')
ncwriteatt(ncid,'DENS_DY','Processing_level','Data manually reviewed')
ncwriteatt(ncid,'DENS_DY','ancillary_variables','DENS_DY_QC')
ncwriteatt(ncid,'DENS_DY','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid,'DENS_DY','sensor_name','SBE37S')
ncwriteatt(ncid,'DENS_DY','sensor_serial_number',inputs.serial)
ncwriteatt(ncid,'DENS_DY','comment','Derived from measured conductivity, temperature, and pressure.')

ncwriteatt(ncid,'DENS_DY_QC','long_name','quality flag')
ncwriteatt(ncid,'DENS_DY_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid,'DENS_DY_QC','valid_min',0)
ncwriteatt(ncid,'DENS_DY_QC','valid_max',5)
%ncwriteatt(ncid,'DENS_DY_QC','valid_max',9)
ncwriteatt(ncid,'DENS_DY_QC','flag_values',int8([0,1,2,3,4,5]))
%ncwriteatt(ncid,'DENS_DY_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
ncwriteatt(ncid,'DENS_DY_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
%ncwriteatt(ncid,'DENS_DY_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')

ncwriteatt(ncid,'PSAL_DY','long_name','sea water salinity')
ncwriteatt(ncid,'PSAL_DY','standard_name','sea_water_practical_salinity')
ncwriteatt(ncid,'PSAL_DY','units','1')
ncwriteatt(ncid,'PSAL_DY','valid_min',25)
ncwriteatt(ncid,'PSAL_DY','valid_max',45)
ncwriteatt(ncid,'PSAL_DY','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid,'PSAL_DY','QC_indicator','Good data')
ncwriteatt(ncid,'PSAL_DY','Processing_level','Data manually reviewed')
ncwriteatt(ncid,'PSAL_DY','ancillary_variables','PSAL_DY_QC')
ncwriteatt(ncid,'PSAL_DY','reference_scale','PSS-78')
ncwriteatt(ncid,'PSAL_DY','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid,'PSAL_DY','sensor_name','SBE37S')
ncwriteatt(ncid,'PSAL_DY','sensor_serial_number',inputs.serial)
ncwriteatt(ncid,'PSAL_DY','comment','In PSU. Derived from measured conductivity, temperature, and pressure.')

ncwriteatt(ncid,'PSAL_DY_QC','long_name','quality flag')
ncwriteatt(ncid,'PSAL_DY_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid,'PSAL_DY_QC','valid_min',0)
ncwriteatt(ncid,'PSAL_DY_QC','valid_max',5)
%ncwriteatt(ncid,'PSAL_DY_QC','valid_max',9)
ncwriteatt(ncid,'PSAL_DY_QC','flag_values',int8([0,1,2,3,4,5]))
%ncwriteatt(ncid,'PSAL_DY_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
ncwriteatt(ncid,'PSAL_DY_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
%ncwriteatt(ncid,'PSAL_DY_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')



% Add global attributes
%ncwriteatt(ncid,'/','data_type','OceanSITES time-series data')
ncwriteatt(ncid,'/','data_type','DisDel time-series data')
ncwriteatt(ncid,'/','format_version','1.3')
ncwriteatt(ncid,'/','date_created',datestr(now,'yyyy-mm-ddTHH:MM:ssZ'))
ncwriteatt(ncid,'/','date_modified',datestr(now,'yyyy-mm-ddTHH:MM:ssZ'))
ncwriteatt(ncid,'/','institution','NOAA/Pacific Marine Environmental Laboratory')
ncwriteatt(ncid,'/','project','Ocean Climate Stations (OCS)')
ncwriteatt(ncid,'/','network','OCS')
ncwriteatt(ncid,'/','wmo_platform_code',platcode)
ncwriteatt(ncid,'/','source','Moored surface buoy')
ncwriteatt(ncid,'/','history',sprintf('%s %s',datestr(now,'yyyy-mm-ddTHH:MM:ssZ'),'data updated at PMEL'))
ncwriteatt(ncid,'/','data_mode','D')
ncwriteatt(ncid,'/','QC_indicator','excellent')
ncwriteatt(ncid,'/','processing_level','Ranges applied, bad data flagged')
ncwriteatt(ncid,'/','references','http://www.oceansites.org, http://www.pmel.noaa.gov/OCS/')
ncwriteatt(ncid,'/','comment',sprintf('To conform to surrounding time-series, Temperatures and Conductivities were adjusted by %+g degrees C and %+g mS/cm, respectively. These offsets are less than or equal to the instrument error.',inputs.adjtemp,inputs.adjcond))
ncwriteatt(ncid,'/','Conventions','OceanSITES Manual 1.3, CF-1.6')
ncwriteatt(ncid,'/','netcdf_version',netcdf.inqLibVers)
ncwriteatt(ncid,'/','naming_authority','OceanSITES')
ncwriteatt(ncid,'/','id',ncid(1:end-3))
ncwriteatt(ncid,'/','cdm_data_type','Station')
ncwriteatt(ncid,'/','time_coverage_start',datestr(double(time(1)),'yyyy-mm-ddTHH:MM:ssZ'))
ncwriteatt(ncid,'/','time_coverage_end',datestr(double(time(end)),'yyyy-mm-ddTHH:MM:ssZ'))
%ncwriteatt(ncid,'/','time_coverage_start',datestr(double(time_hr(1)),'yyyy-mm-ddTHH:MM:ssZ'))
%ncwriteatt(ncid,'/','time_coverage_end',datestr(double(time_hr(end)),'yyyy-mm-ddTHH:MM:ssZ'))
%ncwriteatt(ncid,'/','time_coverage_start',datestr(double(time_dy(1)),'yyyy-mm-ddTHH:MM:ssZ'))
%ncwriteatt(ncid,'/','time_coverage_end',datestr(double(time_dy(end)),'yyyy-mm-ddTHH:MM:ssZ'))
ncwriteatt(ncid,'/','institution_references','http://www.pmel.noaa.gov/')
ncwriteatt(ncid,'/','contact','OCS Data Manager: ocs@noaa.gov')
ncwriteatt(ncid,'/','publisher_name','Nathan Anderson')
ncwriteatt(ncid,'/','publisher_email','nathan.anderson@noaa.gov')
ncwriteatt(ncid,'/','publisher_url','http://www.pmel.noaa.gov/ocs/people')
ncwriteatt(ncid,'/','data_assembly_center','PMEL')
ncwriteatt(ncid,'/','principal_investigator','Dr. Meghan F. Cronin')
ncwriteatt(ncid,'/','principal_investigator_email','meghan.f.cronin@noaa.gov')
ncwriteatt(ncid,'/','principal_investigator_url','http://www.pmel.noaa.gov/people/cronin')
ncwriteatt(ncid,'/','license','These data are made freely available without restriction')
ncwriteatt(ncid,'/','citation','These data were collected and made freely available by the OceanSITES project and the Ocean Climate Stations (OCS) Project Office of NOAA/PMEL')
ncwriteatt(ncid,'/','update_interval','void')
ncwriteatt(ncid,'/','qc_manual','http://www.oceansites.org/docs/oceansites_data_format_reference_manual.pdf')
ncwriteatt(ncid,'/','Data_Source','OCS Project Office/NOAA/PMEL')
ncwriteatt(ncid,'/','acknowledgement',['If you use these data in publications of presentations, please acknowledge the OCS Project Office ', ...
'of NOAA/PMEL.  Also, we would appreciate receiving a preprint and/or reprint of publications utilizing the data for inclusion in our bibliography.  ', ...
'Relevant publications should be sent to: OCS Project Office, NOAA/PMEL/OCRD, 7600 Sand Point Way NE, Seattle, WA 98115 or emailed to: meghan.f.cronin@noaa.gov'])
ncwriteatt(ncid,'/','platform_code',location)
ncwriteatt(ncid,'/','site_code',location)
ncwriteatt(ncid,'/','array',array)
%ncwriteatt(ncid,'/','title',sprintf('OceanSITES Station %s In-Situ %s Resolution Data',location,'10-Minute'))
ncwriteatt(ncid,'/','title',sprintf('OceanSITES Station %s In-Situ %s Resolution Data',location,'Deep SeaCat All'))
ncwriteatt(ncid,'/','geospatial_lon_min',sprintf('%.2f',lons(1)))
ncwriteatt(ncid,'/','geospatial_lon_max',sprintf('%.2f',lons(2)))
ncwriteatt(ncid,'/','geospatial_lat_min',sprintf('%.2f',lats(1)))
ncwriteatt(ncid,'/','geospatial_lat_max',sprintf('%.2f',lats(2)))
ncwriteatt(ncid,'/','area',area)
ncwriteatt(ncid,'/','geospatial_vertical_min',sprintf('%.0f',floor(sal.pressure2depth(min(dft.pres),lat))))
ncwriteatt(ncid,'/','geospatial_vertical_max',sprintf('%.0f',ceil(sal.pressure2depth(max(dft.pres),lat))))
ncwriteatt(ncid,'/','geospatial_vertical_positive','down')
ncwriteatt(ncid,'/','summary',sprintf('This file contains all resolutions of delayed-mode in-situ data from the deep SBE instrument on the OceanSITES Station %s %s %s (%s) deployment.',location,nomloc,datestr(double(time(1)),'yyyy'),upper(inputs.mooring)))

end

