function [] = make_OS()
load('FINAL_OS.mat');

% Create OceanSITES netcdf file with all 10min TP and hourly data.

% First and foremost, correct the QC codes for OceanSITES.
% Highres flags.
flags.T(flags.T==0)=9; flags.C(flags.C==0)=9; flags.P(flags.P==0)=9; flags.S(flags.S==0)=9; flags.D(flags.D==0)=9;
flags.T(flags.T==2)=1; flags.C(flags.C==2)=1; flags.P(flags.P==2)=1; flags.S(flags.S==2)=1; flags.D(flags.D==2)=1;
flags.T(flags.T==3)=2; flags.C(flags.C==3)=2; flags.P(flags.P==3)=2; flags.S(flags.S==3)=2; flags.D(flags.D==3)=2;
flags.T(flags.T==4)=2; flags.C(flags.C==4)=2; flags.P(flags.P==4)=2; flags.S(flags.S==4)=2; flags.D(flags.D==4)=2;
flags.T(flags.T==5)=4; flags.C(flags.C==5)=4; flags.P(flags.P==5)=4; flags.S(flags.S==5)=4; flags.D(flags.D==5)=4;
% Hourly flags.
flags.T_hr(flags.T_hr==0)=9; flags.C_hr(flags.C_hr==0)=9; flags.P_hr(flags.P_hr==0)=9; flags.S_hr(flags.S_hr==0)=9; flags.D_hr(flags.D_hr==0)=9;
flags.T_hr(flags.T_hr==2)=1; flags.C_hr(flags.C_hr==2)=1; flags.P_hr(flags.P_hr==2)=1; flags.S_hr(flags.S_hr==2)=1; flags.D_hr(flags.D_hr==2)=1;
flags.T_hr(flags.T_hr==3)=2; flags.C_hr(flags.C_hr==3)=2; flags.P_hr(flags.P_hr==3)=2; flags.S_hr(flags.S_hr==3)=2; flags.D_hr(flags.D_hr==3)=2;
flags.T_hr(flags.T_hr==4)=2; flags.C_hr(flags.C_hr==4)=2; flags.P_hr(flags.P_hr==4)=2; flags.S_hr(flags.S_hr==4)=2; flags.D_hr(flags.D_hr==4)=2;
flags.T_hr(flags.T_hr==5)=4; flags.C_hr(flags.C_hr==5)=4; flags.P_hr(flags.P_hr==5)=4; flags.S_hr(flags.S_hr==5)=4; flags.D_hr(flags.D_hr==5)=4;

% First construct the name of the netcdf file.
if strcmp(inputs.mooring(1:2),'pa')
    location = 'PAPA';
    nomloc = '(nominally 50.1N, 144.9W)';
    lat = 50.1; lon = -144.9;
    lats = [50,50.2]; lons = [-145,-144.7];
    platcode = '4800400';
    array = 'STATION-P';
    area = 'North Pacific';
elseif strcmp(inputs.mooring(1:2),'ke')
    location = 'KEO';
    nomloc = '(nominally 32.3N, 144.6E)';
    lat = 32.3; lon = 144.6;
    lats = [32.1,32.65]; lons = [144.35,144.75];
    platcode = '2800401';
    array = 'KUROSHIO EXTENSION';
    area = 'Western Pacific Kuroshio Extension';
end

% Name of file.
ncid1 = sprintf('OS_%s_%s%s_D_DEEP-SEACAT-10min.nc',location,inputs.startdt(1:4),upper(inputs.mooring));
ncid2 = sprintf('OS_%s_%s%s_D_DEEP-SEACAT-1hr.nc',location,inputs.startdt(1:4),upper(inputs.mooring));
delete(ncid1); delete(ncid2);

% Move old file to keep out of the way.
% if ~isempty(dir(ncid1))
%     if ~exist('OLD_NC','dir')
%         mkdir('OLD_NC');
%     end
%     movefile(ncid1,'OLD_NC');
% end
% if ~isempty(dir(ncid2))
%     if ~exist('OLD_NC','dir')
%         mkdir('OLD_NC');
%     end
%     movefile(ncid2,'OLD_NC');
% end

% Create nc file and integrate coordinate variables (i.e. both dimensions and variables).
nccreate(ncid1,'TIME','Dimensions',{'TIME',inf},'Format','netcdf4_classic')
ncwrite(ncid1,'TIME',time-712224)
nccreate(ncid1,'LATITUDE','Dimensions',{'LATITUDE',1},'Format','netcdf4_classic','DataType','single')
ncwrite(ncid1,'LATITUDE',lat)
nccreate(ncid1,'LONGITUDE','Dimensions',{'LONGITUDE',1},'Format','netcdf4_classic','DataType','single')
ncwrite(ncid1,'LONGITUDE',lon)
nccreate(ncid1,'DEPTH','Dimensions',{'DEPTH',1},'Format','netcdf4_classic','DataType','single')
ncwrite(ncid1,'DEPTH',round(inputs.nominal_depths))

nccreate(ncid2,'TIME','Dimensions',{'TIME',inf},'Format','netcdf4_classic')
ncwrite(ncid2,'TIME',time_hr-712224)
nccreate(ncid2,'LATITUDE','Dimensions',{'LATITUDE',1},'Format','netcdf4_classic','DataType','single')
ncwrite(ncid2,'LATITUDE',lat)
nccreate(ncid2,'LONGITUDE','Dimensions',{'LONGITUDE',1},'Format','netcdf4_classic','DataType','single')
ncwrite(ncid2,'LONGITUDE',lon)
nccreate(ncid2,'DEPTH','Dimensions',{'DEPTH',1},'Format','netcdf4_classic','DataType','single')
ncwrite(ncid2,'DEPTH',round(inputs.nominal_depths))

% 10 Minute
nccreate(ncid1,'TEMP','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','netcdf4_classic','DataType','single','FillValue',NaN)
ncwrite(ncid1,'TEMP',reshape(dft.temp,1,1,1,size(time,1)))
nccreate(ncid1,'TEMP_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','netcdf4_classic','DataType','int8','FillValue',-128)
ncwrite(ncid1,'TEMP_QC',reshape(flags.T,1,1,1,size(time,1)))

nccreate(ncid1,'PRES','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','netcdf4_classic','DataType','single','FillValue',NaN)
ncwrite(ncid1,'PRES',reshape(dft.pres,1,1,1,size(time,1)))
nccreate(ncid1,'PRES_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','netcdf4_classic','DataType','int8','FillValue',-128)
ncwrite(ncid1,'PRES_QC',reshape(flags.P,1,1,1,size(time,1)))

%nccreate(ncid,'CNDC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','netcdf4_classic','DataType','single','FillValue',NaN)
%ncwrite(ncid,'CNDC',reshape(dft.cond,1,1,1,size(time,1)))
%nccreate(ncid,'CNDC_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','netcdf4_classic','DataType','int8','FillValue',-128)
%ncwrite(ncid,'CNDC_QC',reshape(flags.C,1,1,1,size(time,1)))

%nccreate(ncid,'DENS','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','netcdf4_classic','DataType','single','FillValue',NaN)
%ncwrite(ncid,'DENS',reshape(dft.dens,1,1,1,size(time,1)))
%nccreate(ncid,'DENS_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','netcdf4_classic','DataType','int8','FillValue',-128)
%ncwrite(ncid,'DENS_QC',reshape(flags.D,1,1,1,size(time,1)))

%nccreate(ncid,'PSAL','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','netcdf4_classic','DataType','single','FillValue',NaN)
%ncwrite(ncid,'PSAL',reshape(dft.sal,1,1,1,size(time,1)))
%nccreate(ncid,'PSAL_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',inf},'Format','netcdf4_classic','DataType','int8','FillValue',-128)
%ncwrite(ncid,'PSAL_QC',reshape(flags.S,1,1,1,size(time,1)))


% Hourly
nccreate(ncid2,'TEMP','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',size(time_hr,1)},'Format','netcdf4_classic','DataType','single','FillValue',NaN)
ncwrite(ncid2,'TEMP',reshape(flt.temp,1,1,1,size(time_hr,1)))
nccreate(ncid2,'TEMP_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',size(time_hr,1)},'Format','netcdf4_classic','DataType','int8','FillValue',-128)
ncwrite(ncid2,'TEMP_QC',reshape(flags.T_hr,1,1,1,size(time_hr,1)))

nccreate(ncid2,'PRES','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',size(time_hr,1)},'Format','netcdf4_classic','DataType','single','FillValue',NaN)
ncwrite(ncid2,'PRES',reshape(flt.pres,1,1,1,size(time_hr,1)))
nccreate(ncid2,'PRES_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',size(time_hr,1)},'Format','netcdf4_classic','DataType','int8','FillValue',-128)
ncwrite(ncid2,'PRES_QC',reshape(flags.P_hr,1,1,1,size(time_hr,1)))

nccreate(ncid2,'CNDC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',size(time_hr,1)},'Format','netcdf4_classic','DataType','single','FillValue',NaN)
ncwrite(ncid2,'CNDC',reshape(flt.cond,1,1,1,size(time_hr,1)))
nccreate(ncid2,'CNDC_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',size(time_hr,1)},'Format','netcdf4_classic','DataType','int8','FillValue',-128)
ncwrite(ncid2,'CNDC_QC',reshape(flags.C_hr,1,1,1,size(time_hr,1)))

nccreate(ncid2,'DENS','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',size(time_hr,1)},'Format','netcdf4_classic','DataType','single','FillValue',NaN)
ncwrite(ncid2,'DENS',reshape(flt.dens,1,1,1,size(time_hr,1)))
nccreate(ncid2,'DENS_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',size(time_hr,1)},'Format','netcdf4_classic','DataType','int8','FillValue',-128)
ncwrite(ncid2,'DENS_QC',reshape(flags.D_hr,1,1,1,size(time_hr,1)))

nccreate(ncid2,'PSAL','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',size(time_hr,1)},'Format','netcdf4_classic','DataType','single','FillValue',NaN)
ncwrite(ncid2,'PSAL',reshape(flt.sal,1,1,1,size(time_hr,1)))
nccreate(ncid2,'PSAL_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME',size(time_hr,1)},'Format','netcdf4_classic','DataType','int8','FillValue',-128)
ncwrite(ncid2,'PSAL_QC',reshape(flags.S_hr,1,1,1,size(time_hr,1)))

% Daily
%nccreate(ncid,'TEMP_DY','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','netcdf4_classic','DataType','single','FillValue',NaN)
%ncwrite(ncid,'TEMP_DY',reshape(davg.temp,1,1,1,size(time_dy,1)))
%nccreate(ncid,'TEMP_DY_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','netcdf4_classic','DataType','int8','FillValue',-128)
%ncwrite(ncid,'TEMP_DY_QC',reshape(flags.T_dy,1,1,1,size(time_dy,1)))

%nccreate(ncid,'PRES_DY','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','netcdf4_classic','DataType','single','FillValue',NaN)
%ncwrite(ncid,'PRES_DY',reshape(davg.pres,1,1,1,size(time_dy,1)))
%nccreate(ncid,'PRES_DY_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','netcdf4_classic','DataType','int8','FillValue',-128)
%ncwrite(ncid,'PRES_DY_QC',reshape(flags.P_dy,1,1,1,size(time_dy,1)))

%nccreate(ncid,'CNDC_DY','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','netcdf4_classic','DataType','single','FillValue',NaN)
%ncwrite(ncid,'CNDC_DY',reshape(davg.cond,1,1,1,size(time_dy,1)))
%nccreate(ncid,'CNDC_DY_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','netcdf4_classic','DataType','int8','FillValue',-128)
%ncwrite(ncid,'CNDC_DY_QC',reshape(flags.C_dy,1,1,1,size(time_dy,1)))

%nccreate(ncid,'DENS_DY','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','netcdf4_classic','DataType','single','FillValue',NaN)
%ncwrite(ncid,'DENS_DY',reshape(davg.dens,1,1,1,size(time_dy,1)))
%nccreate(ncid,'DENS_DY_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','netcdf4_classic','DataType','int8','FillValue',-128)
%ncwrite(ncid,'DENS_DY_QC',reshape(flags.D_dy,1,1,1,size(time_dy,1)))

%nccreate(ncid,'PSAL_DY','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','netcdf4_classic','DataType','single','FillValue',NaN)
%ncwrite(ncid,'PSAL_DY',reshape(davg.sal,1,1,1,size(time_dy,1)))
%nccreate(ncid,'PSAL_DY_QC','Dimensions',{'LONGITUDE',1,'LATITUDE',1,'DEPTH',1,'TIME_DY',size(time_dy,1)},'Format','netcdf4_classic','DataType','int8','FillValue',-128)
%ncwrite(ncid,'PSAL_DY_QC',reshape(flags.S_dy,1,1,1,size(time_dy,1)))



% Add attributes to each variable
ncwriteatt(ncid1,'TIME','long_name','time')
ncwriteatt(ncid1,'TIME','standard_name','time')
ncwriteatt(ncid1,'TIME','units','days since 1950-01-01T00:00:00Z')
ncwriteatt(ncid1,'TIME','valid_min',time(1)-712224)
ncwriteatt(ncid1,'TIME','valid_max',time(end)-712224)
ncwriteatt(ncid1,'TIME','point_spacing','even')
ncwriteatt(ncid1,'TIME','QC_indicator','Good data')
ncwriteatt(ncid1,'TIME','Processing_level','Ranges applied, bad data flagged')
ncwriteatt(ncid1,'TIME','Uncertainty','None')
ncwriteatt(ncid1,'TIME','axis','T')

%ncwriteatt(ncid,'TIME_DY','long_name','time of measurement')
%ncwriteatt(ncid,'TIME_DY','standard_name','time')
%ncwriteatt(ncid,'TIME_DY','units','days since 1950-01-01T00:00:00Z')
%ncwriteatt(ncid,'TIME_DY','valid_min',time_dy(1)-712224)
%ncwriteatt(ncid,'TIME_DY','valid_max',time_dy(end)-712224)
%ncwriteatt(ncid,'TIME_DY','point_spacing','even')
%ncwriteatt(ncid,'TIME_DY','QC_indicator','Good data')
%ncwriteatt(ncid,'TIME_DY','Processing_level','Ranges applied, bad data flagged')
%ncwriteatt(ncid,'TIME_DY','Uncertainty','None')
%ncwriteatt(ncid,'TIME_DY','axis','T')

ncwriteatt(ncid1,'LATITUDE','long_name','Anchor Latitude')
ncwriteatt(ncid1,'LATITUDE','standard_name','latitude')
ncwriteatt(ncid1,'LATITUDE','units','degrees_north')
ncwriteatt(ncid1,'LATITUDE','valid_min',-90)
ncwriteatt(ncid1,'LATITUDE','valid_max',90)
ncwriteatt(ncid1,'LATITUDE','QC_indicator','nominal vlaue')
ncwriteatt(ncid1,'LATITUDE','Processing_level','Data manually reviewed')
ncwriteatt(ncid1,'LATITUDE','Uncertainty','None')
ncwriteatt(ncid1,'LATITUDE','axis','Y')
ncwriteatt(ncid1,'LATITUDE','reference','WGS84')
ncwriteatt(ncid1,'LATITUDE','coordinate_reference_frame','urn:ogc:crs:EPSG::4326')

ncwriteatt(ncid1,'LONGITUDE','long_name','Anchor Longitude')
ncwriteatt(ncid1,'LONGITUDE','standard_name','longitude')
ncwriteatt(ncid1,'LONGITUDE','units','degrees_east')
ncwriteatt(ncid1,'LONGITUDE','valid_min',-180)
ncwriteatt(ncid1,'LONGITUDE','valid_max',180)
ncwriteatt(ncid1,'LONGITUDE','QC_indicator','nominal value')
ncwriteatt(ncid1,'LONGITUDE','Processing_level','Data manually reviewed')
ncwriteatt(ncid1,'LONGITUDE','Uncertainty','None')
ncwriteatt(ncid1,'LONGITUDE','axis','X')
ncwriteatt(ncid1,'LONGITUDE','reference','WGS84')
ncwriteatt(ncid1,'LONGITUDE','coordinate_reference_frame','urn:ogc:crs:EPSG::4326')

ncwriteatt(ncid1,'DEPTH','long_name','Depth of each measurement')
ncwriteatt(ncid1,'DEPTH','standard_name','depth')
ncwriteatt(ncid1,'DEPTH','units','meters')
ncwriteatt(ncid1,'DEPTH','positive','down')
ncwriteatt(ncid1,'DEPTH','valid_min',round(inputs.nominal_depths(1)))
ncwriteatt(ncid1,'DEPTH','valid_max',round(inputs.nominal_depths(1)))
ncwriteatt(ncid1,'DEPTH','QC_indicator','nominal value')
ncwriteatt(ncid1,'DEPTH','Processing_level','Data manually reviewed')
ncwriteatt(ncid1,'DEPTH','Uncertainty','Approximate value')
ncwriteatt(ncid1,'DEPTH','axis','Z')
ncwriteatt(ncid1,'DEPTH','reference','sea_level')
ncwriteatt(ncid1,'DEPTH','coordinate_reference_frame','urn:ogc:crs:EPSG::5831')

ncwriteatt(ncid2,'TIME','long_name','time')
ncwriteatt(ncid2,'TIME','standard_name','time')
ncwriteatt(ncid2,'TIME','units','days since 1950-01-01T00:00:00Z')
ncwriteatt(ncid2,'TIME','valid_min',time_hr(1)-712224)
ncwriteatt(ncid2,'TIME','valid_max',time_hr(end)-712224)
ncwriteatt(ncid2,'TIME','point_spacing','even')
ncwriteatt(ncid2,'TIME','QC_indicator','Good data')
ncwriteatt(ncid2,'TIME','Processing_level','Ranges applied, bad data flagged')
ncwriteatt(ncid2,'TIME','Uncertainty','None')
ncwriteatt(ncid2,'TIME','axis','T')

ncwriteatt(ncid2,'LATITUDE','long_name','Anchor Latitude')
ncwriteatt(ncid2,'LATITUDE','standard_name','latitude')
ncwriteatt(ncid2,'LATITUDE','units','degrees_north')
ncwriteatt(ncid2,'LATITUDE','valid_min',-90)
ncwriteatt(ncid2,'LATITUDE','valid_max',90)
ncwriteatt(ncid2,'LATITUDE','QC_indicator','nominal vlaue')
ncwriteatt(ncid2,'LATITUDE','Processing_level','Data manually reviewed')
ncwriteatt(ncid2,'LATITUDE','Uncertainty','None')
ncwriteatt(ncid2,'LATITUDE','axis','Y')
ncwriteatt(ncid2,'LATITUDE','reference','WGS84')
ncwriteatt(ncid2,'LATITUDE','coordinate_reference_frame','urn:ogc:crs:EPSG::4326')

ncwriteatt(ncid2,'LONGITUDE','long_name','Anchor Longitude')
ncwriteatt(ncid2,'LONGITUDE','standard_name','longitude')
ncwriteatt(ncid2,'LONGITUDE','units','degrees_east')
ncwriteatt(ncid2,'LONGITUDE','valid_min',-180)
ncwriteatt(ncid2,'LONGITUDE','valid_max',180)
ncwriteatt(ncid2,'LONGITUDE','QC_indicator','nominal value')
ncwriteatt(ncid2,'LONGITUDE','Processing_level','Data manually reviewed')
ncwriteatt(ncid2,'LONGITUDE','Uncertainty','None')
ncwriteatt(ncid2,'LONGITUDE','axis','X')
ncwriteatt(ncid2,'LONGITUDE','reference','WGS84')
ncwriteatt(ncid2,'LONGITUDE','coordinate_reference_frame','urn:ogc:crs:EPSG::4326')

ncwriteatt(ncid2,'DEPTH','long_name','Depth of each measurement')
ncwriteatt(ncid2,'DEPTH','standard_name','depth')
ncwriteatt(ncid2,'DEPTH','units','meters')
ncwriteatt(ncid2,'DEPTH','positive','down')
ncwriteatt(ncid2,'DEPTH','valid_min',round(inputs.nominal_depths(1)))
ncwriteatt(ncid2,'DEPTH','valid_max',round(inputs.nominal_depths(1)))
ncwriteatt(ncid2,'DEPTH','QC_indicator','nominal value')
ncwriteatt(ncid2,'DEPTH','Processing_level','Data manually reviewed')
ncwriteatt(ncid2,'DEPTH','Uncertainty','Approximate value')
ncwriteatt(ncid2,'DEPTH','axis','Z')
ncwriteatt(ncid2,'DEPTH','reference','sea_level')
ncwriteatt(ncid2,'DEPTH','coordinate_reference_frame','urn:ogc:crs:EPSG::5831')

% Write highres attributes.
ncwriteatt(ncid1,'TEMP','long_name','sea water temperature in-situ ITS-90 scale')
ncwriteatt(ncid1,'TEMP','standard_name','sea_water_temperature')
ncwriteatt(ncid1,'TEMP','units','degree_Celsius')
ncwriteatt(ncid1,'TEMP','valid_min',-2)
ncwriteatt(ncid1,'TEMP','valid_max',40)
ncwriteatt(ncid1,'TEMP','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid1,'TEMP','QC_indicator','Good data')
ncwriteatt(ncid1,'TEMP','Processing_level','Data manually reviewed')
ncwriteatt(ncid1,'TEMP','ancillary_variables','TEMP_QC')
ncwriteatt(ncid1,'TEMP','reference_scale','ITS-90')
ncwriteatt(ncid1,'TEMP','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid1,'TEMP','sensor_name','SBE37S')
ncwriteatt(ncid1,'TEMP','sensor_serial_number',inputs.serial)

ncwriteatt(ncid1,'TEMP_QC','long_name','quality flag')
ncwriteatt(ncid1,'TEMP_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid1,'TEMP_QC','valid_min',0)
%ncwriteatt(ncid1,'TEMP_QC','valid_max',5)
ncwriteatt(ncid1,'TEMP_QC','valid_max',9)
%ncwriteatt(ncid1,'TEMP_QC','flag_values',int8([0,1,2,3,4,5]))
ncwriteatt(ncid1,'TEMP_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
%ncwriteatt(ncid1,'TEMP_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
ncwriteatt(ncid1,'TEMP_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')

ncwriteatt(ncid1,'PRES','long_name','sea water pressure')
ncwriteatt(ncid1,'PRES','standard_name','sea_water_pressure')
ncwriteatt(ncid1,'PRES','units','decibar')
ncwriteatt(ncid1,'PRES','valid_min',0)
ncwriteatt(ncid1,'PRES','valid_max',6000)
ncwriteatt(ncid1,'PRES','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid1,'PRES','QC_indicator','Good data')
ncwriteatt(ncid1,'PRES','Processing_level','Data manually reviewed')
ncwriteatt(ncid1,'PRES','ancillary_variables','PRES_QC')
ncwriteatt(ncid1,'PRES','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid1,'PRES','sensor_name','SBE37S')
ncwriteatt(ncid1,'PRES','sensor_serial_number',inputs.serial_pressure)

ncwriteatt(ncid1,'PRES_QC','long_name','quality flag')
ncwriteatt(ncid1,'PRES_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid1,'PRES_QC','valid_min',0)
%ncwriteatt(ncid1,'PRES_QC','valid_max',5)
ncwriteatt(ncid1,'PRES_QC','valid_max',9)
%ncwriteatt(ncid1,'PRES_QC','flag_values',int8([0,1,2,3,4,5]))
ncwriteatt(ncid1,'PRES_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
%ncwriteatt(ncid1,'PRES_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
ncwriteatt(ncid1,'PRES_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Added for OS 10min.
% ncwriteatt(ncid,'CNDC','long_name','sea water conductivity')
% ncwriteatt(ncid,'CNDC','standard_name','sea_water_electrical_conductivity')
% ncwriteatt(ncid,'CNDC','units','S/m')
% ncwriteatt(ncid,'CNDC','valid_min',0)
% ncwriteatt(ncid,'CNDC','valid_max',7)
% ncwriteatt(ncid,'CNDC','coordinates','TIME DEPTH LATITUDE LONGITUDE')
% ncwriteatt(ncid,'CNDC','QC_indicator','Good data')
% ncwriteatt(ncid,'CNDC','Processing_level','Data manually reviewed')
% ncwriteatt(ncid,'CNDC','ancillary_variables','CNDC_QC')
% ncwriteatt(ncid,'CNDC','sensor_mount','mounted_on_mooring_line')
% ncwriteatt(ncid,'CNDC','sensor_name','SBE37S')
% ncwriteatt(ncid,'CNDC','sensor_serial_number',inputs.serial)
% 
% ncwriteatt(ncid,'CNDC_QC','long_name','quality flag')
% ncwriteatt(ncid,'CNDC_QC','conventions','OceanSITES reference table 2')
% ncwriteatt(ncid,'CNDC_QC','valid_min',0)
% %ncwriteatt(ncid,'CNDC_QC','valid_max',5)
% ncwriteatt(ncid,'CNDC_QC','valid_max',9)
% %ncwriteatt(ncid,'CNDC_QC','flag_values',int8([0,1,2,3,4,5]))
% ncwriteatt(ncid,'CNDC_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
% %ncwriteatt(ncid,'CNDC_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
% ncwriteatt(ncid,'CNDC_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')
% 
% if strcmp(inputs.mooring(1:2),'pa')
%     ncwriteatt(ncid,'DENS','long_name','sigma-theta (potential density adjusted to 4000m)')
% elseif strcmp(inputs.mooring(1:2),'ke')
%     ncwriteatt(ncid,'DENS','long_name','sigma-theta (potential density adjusted to 6000m)')
% end
% ncwriteatt(ncid,'DENS','standard_name','sea_water_sigma_theta')
% ncwriteatt(ncid,'DENS','units','kg m-3')
% ncwriteatt(ncid,'DENS','valid_min',0)
% ncwriteatt(ncid,'DENS','valid_max',50)
% ncwriteatt(ncid,'DENS','coordinates','TIME DEPTH LATITUDE LONGITUDE')
% ncwriteatt(ncid,'DENS','QC_indicator','Good data')
% ncwriteatt(ncid,'DENS','Processing_level','Data manually reviewed')
% ncwriteatt(ncid,'DENS','ancillary_variables','DENS_QC')
% ncwriteatt(ncid,'DENS','sensor_mount','mounted_on_mooring_line')
% ncwriteatt(ncid,'DENS','sensor_name','SBE37S')
% ncwriteatt(ncid,'DENS','sensor_serial_number',inputs.serial)
% ncwriteatt(ncid,'DENS','comment','Derived from measured conductivity, temperature, and pressure.')
% 
% ncwriteatt(ncid,'DENS_QC','long_name','quality flag')
% ncwriteatt(ncid,'DENS_QC','conventions','OceanSITES reference table 2')
% ncwriteatt(ncid,'DENS_QC','valid_min',0)
% %ncwriteatt(ncid,'DENS_QC','valid_max',5)
% ncwriteatt(ncid,'DENS_QC','valid_max',9)
% %ncwriteatt(ncid,'DENS_QC','flag_values',int8([0,1,2,3,4,5]))
% ncwriteatt(ncid,'DENS_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
% %ncwriteatt(ncid,'DENS_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
% ncwriteatt(ncid,'DENS_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')
% 
% ncwriteatt(ncid,'PSAL','long_name','sea water salinity')
% ncwriteatt(ncid,'PSAL','standard_name','sea_water_practical_salinity')
% ncwriteatt(ncid,'PSAL','units','1')
% ncwriteatt(ncid,'PSAL','valid_min',25)
% ncwriteatt(ncid,'PSAL','valid_max',45)
% ncwriteatt(ncid,'PSAL','coordinates','TIME DEPTH LATITUDE LONGITUDE')
% ncwriteatt(ncid,'PSAL','QC_indicator','Good data')
% ncwriteatt(ncid,'PSAL','Processing_level','Data manually reviewed')
% ncwriteatt(ncid,'PSAL','ancillary_variables','PSAL_QC')
% ncwriteatt(ncid,'PSAL','reference_scale','PSS-78')
% ncwriteatt(ncid,'PSAL','sensor_mount','mounted_on_mooring_line')
% ncwriteatt(ncid,'PSAL','sensor_name','SBE37S')
% ncwriteatt(ncid,'PSAL','sensor_serial_number',inputs.serial)
% ncwriteatt(ncid,'PSAL','comment','In PSU. Derived from measured conductivity, temperature, and pressure.')
% 
% ncwriteatt(ncid,'PSAL_QC','long_name','quality flag')
% ncwriteatt(ncid,'PSAL_QC','conventions','OceanSITES reference table 2')
% ncwriteatt(ncid,'PSAL_QC','valid_min',0)
% %ncwriteatt(ncid,'PSAL_QC','valid_max',5)
% ncwriteatt(ncid,'PSAL_QC','valid_max',9)
% %ncwriteatt(ncid,'PSAL_QC','flag_values',int8([0,1,2,3,4,5]))
% ncwriteatt(ncid,'PSAL_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
% %ncwriteatt(ncid,'PSAL_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
% ncwriteatt(ncid,'PSAL_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')
% 



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Hourly
ncwriteatt(ncid2,'TEMP','long_name','sea water temperature in-situ ITS-90 scale')
ncwriteatt(ncid2,'TEMP','standard_name','sea_water_temperature')
ncwriteatt(ncid2,'TEMP','units','degree_Celsius')
ncwriteatt(ncid2,'TEMP','valid_min',-2)
ncwriteatt(ncid2,'TEMP','valid_max',40)
ncwriteatt(ncid2,'TEMP','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid2,'TEMP','QC_indicator','Good data')
ncwriteatt(ncid2,'TEMP','Processing_level','Data manually reviewed')
ncwriteatt(ncid2,'TEMP','ancillary_variables','TEMP_QC')
ncwriteatt(ncid2,'TEMP','reference_scale','ITS-90')
ncwriteatt(ncid2,'TEMP','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid2,'TEMP','sensor_name','SBE37S')
ncwriteatt(ncid2,'TEMP','sensor_serial_number',inputs.serial)
 
ncwriteatt(ncid2,'TEMP_QC','long_name','quality flag')
ncwriteatt(ncid2,'TEMP_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid2,'TEMP_QC','valid_min',0)
% ncwriteatt(ncid2,'TEMP_QC','valid_max',5)
ncwriteatt(ncid2,'TEMP_QC','valid_max',9)
% ncwriteatt(ncid2,'TEMP_QC','flag_values',int8([0,1,2,3,4,5]))
ncwriteatt(ncid2,'TEMP_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
% ncwriteatt(ncid2,'TEMP_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
ncwriteatt(ncid2,'TEMP_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')
 
ncwriteatt(ncid2,'PRES','long_name','sea water pressure')
ncwriteatt(ncid2,'PRES','standard_name','sea_water_pressure')
ncwriteatt(ncid2,'PRES','units','decibar')
ncwriteatt(ncid2,'PRES','valid_min',0)
ncwriteatt(ncid2,'PRES','valid_max',6000)
ncwriteatt(ncid2,'PRES','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid2,'PRES','QC_indicator','Good data')
ncwriteatt(ncid2,'PRES','Processing_level','Data manually reviewed')
ncwriteatt(ncid2,'PRES','ancillary_variables','PRES_QC')
ncwriteatt(ncid2,'PRES','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid2,'PRES','sensor_name','SBE37S')
ncwriteatt(ncid2,'PRES','sensor_serial_number',inputs.serial_pressure)

ncwriteatt(ncid2,'PRES_QC','long_name','quality flag')
ncwriteatt(ncid2,'PRES_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid2,'PRES_QC','valid_min',0)
% ncwriteatt(ncid2,'PRES_QC','valid_max',5)
ncwriteatt(ncid2,'PRES_QC','valid_max',9)
% ncwriteatt(ncid2,'PRES_QC','flag_values',int8([0,1,2,3,4,5]))
ncwriteatt(ncid2,'PRES_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
% ncwriteatt(ncid2,'PRES_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
ncwriteatt(ncid2,'PRES_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')
 
ncwriteatt(ncid2,'CNDC','long_name','sea water conductivity')
ncwriteatt(ncid2,'CNDC','standard_name','sea_water_electrical_conductivity')
ncwriteatt(ncid2,'CNDC','units','S/m')
ncwriteatt(ncid2,'CNDC','valid_min',0)
ncwriteatt(ncid2,'CNDC','valid_max',7)
ncwriteatt(ncid2,'CNDC','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid2,'CNDC','QC_indicator','Good data')
ncwriteatt(ncid2,'CNDC','Processing_level','Data manually reviewed')
ncwriteatt(ncid2,'CNDC','ancillary_variables','CNDC_QC')
ncwriteatt(ncid2,'CNDC','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid2,'CNDC','sensor_name','SBE37S')
ncwriteatt(ncid2,'CNDC','sensor_serial_number',inputs.serial)
 
ncwriteatt(ncid2,'CNDC_QC','long_name','quality flag')
ncwriteatt(ncid2,'CNDC_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid2,'CNDC_QC','valid_min',0)
% ncwriteatt(ncid2,'CNDC_QC','valid_max',5)
ncwriteatt(ncid2,'CNDC_QC','valid_max',9)
% ncwriteatt(ncid2,'CNDC_QC','flag_values',int8([0,1,2,3,4,5]))
ncwriteatt(ncid2,'CNDC_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
% ncwriteatt(ncid2,'CNDC_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
ncwriteatt(ncid2,'CNDC_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')

if strcmp(inputs.mooring(1:2),'pa')
  ncwriteatt(ncid2,'DENS','long_name','sigma-theta (potential density adjusted to 4000m)')
elseif strcmp(inputs.mooring(1:2),'ke')
  ncwriteatt(ncid2,'DENS','long_name','sigma-theta (potential density adjusted to 6000m)')
end
ncwriteatt(ncid2,'DENS','standard_name','sea_water_sigma_theta')
ncwriteatt(ncid2,'DENS','units','kg m-3')
ncwriteatt(ncid2,'DENS','valid_min',0)
ncwriteatt(ncid2,'DENS','valid_max',100)
ncwriteatt(ncid2,'DENS','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid2,'DENS','QC_indicator','Good data')
ncwriteatt(ncid2,'DENS','Processing_level','Data manually reviewed')
ncwriteatt(ncid2,'DENS','ancillary_variables','DENS_QC')
ncwriteatt(ncid2,'DENS','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid2,'DENS','sensor_name','SBE37S')
ncwriteatt(ncid2,'DENS','sensor_serial_number',inputs.serial)
ncwriteatt(ncid2,'DENS','comment','Derived from measured conductivity, temperature, and pressure.')
 
ncwriteatt(ncid2,'DENS_QC','long_name','quality flag')
ncwriteatt(ncid2,'DENS_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid2,'DENS_QC','valid_min',0)
% ncwriteatt(ncid2,'DENS_QC','valid_max',5)
ncwriteatt(ncid2,'DENS_QC','valid_max',9)
% ncwriteatt(ncid2,'DENS_QC','flag_values',int8([0,1,2,3,4,5]))
ncwriteatt(ncid2,'DENS_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
% ncwriteatt(ncid2,'DENS_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
ncwriteatt(ncid2,'DENS_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')
 
ncwriteatt(ncid2,'PSAL','long_name','sea water salinity')
ncwriteatt(ncid2,'PSAL','standard_name','sea_water_practical_salinity')
ncwriteatt(ncid2,'PSAL','units','1')
ncwriteatt(ncid2,'PSAL','valid_min',25)
ncwriteatt(ncid2,'PSAL','valid_max',45)
ncwriteatt(ncid2,'PSAL','coordinates','TIME DEPTH LATITUDE LONGITUDE')
ncwriteatt(ncid2,'PSAL','QC_indicator','Good data')
ncwriteatt(ncid2,'PSAL','Processing_level','Data manually reviewed')
ncwriteatt(ncid2,'PSAL','ancillary_variables','PSAL_QC')
ncwriteatt(ncid2,'PSAL','reference_scale','PSS-78')
ncwriteatt(ncid2,'PSAL','sensor_mount','mounted_on_mooring_line')
ncwriteatt(ncid2,'PSAL','sensor_name','SBE37S')
ncwriteatt(ncid2,'PSAL','sensor_serial_number',inputs.serial)
ncwriteatt(ncid2,'PSAL','comment','Derived from measured conductivity, temperature, and pressure.')
 
ncwriteatt(ncid2,'PSAL_QC','long_name','quality flag')
ncwriteatt(ncid2,'PSAL_QC','conventions','OceanSITES reference table 2')
ncwriteatt(ncid2,'PSAL_QC','valid_min',0)
% ncwriteatt(ncid2,'PSAL_QC','valid_max',5)
ncwriteatt(ncid2,'PSAL_QC','valid_max',9)
% ncwriteatt(ncid2,'PSAL_QC','flag_values',int8([0,1,2,3,4,5]))
ncwriteatt(ncid2,'PSAL_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
% ncwriteatt(ncid2,'PSAL_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
ncwriteatt(ncid2,'PSAL_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')
 
 
 
% % Daily
% ncwriteatt(ncid,'TEMP_DY','long_name','sea water temperature in-situ ITS-90 scale')
% ncwriteatt(ncid,'TEMP_DY','standard_name','sea_water_temperature')
% ncwriteatt(ncid,'TEMP_DY','units','degree_Celsius')
% ncwriteatt(ncid,'TEMP_DY','valid_min',-2)
% ncwriteatt(ncid,'TEMP_DY','valid_max',40)
% ncwriteatt(ncid,'TEMP_DY','coordinates','TIME DEPTH LATITUDE LONGITUDE')
% ncwriteatt(ncid,'TEMP_DY','QC_indicator','Good data')
% ncwriteatt(ncid,'TEMP_DY','Processing_level','Data manually reviewed')
% ncwriteatt(ncid,'TEMP_DY','ancillary_variables','TEMP_DY_QC')
% ncwriteatt(ncid,'TEMP_DY','reference_scale','ITS-90')
% ncwriteatt(ncid,'TEMP_DY','sensor_mount','mounted_on_mooring_line')
% ncwriteatt(ncid,'TEMP_DY','sensor_name','SBE37S')
% ncwriteatt(ncid,'TEMP_DY','sensor_serial_number',inputs.serial)
% 
% ncwriteatt(ncid,'TEMP_DY_QC','long_name','quality flag')
% ncwriteatt(ncid,'TEMP_DY_QC','conventions','OceanSITES reference table 2')
% ncwriteatt(ncid,'TEMP_DY_QC','valid_min',0)
% ncwriteatt(ncid,'TEMP_DY_QC','valid_max',5)
% %ncwriteatt(ncid,'TEMP_DY_QC','valid_max',9)
% ncwriteatt(ncid,'TEMP_DY_QC','flag_values',int8([0,1,2,3,4,5]))
% %ncwriteatt(ncid,'TEMP_DY_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
% ncwriteatt(ncid,'TEMP_DY_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
% %ncwriteatt(ncid,'TEMP_DY_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')
% 
% ncwriteatt(ncid,'PRES_DY','long_name','sea water pressure')
% ncwriteatt(ncid,'PRES_DY','standard_name','sea_water_pressure')
% ncwriteatt(ncid,'PRES_DY','units','decibar')
% ncwriteatt(ncid,'PRES_DY','valid_min',0)
% ncwriteatt(ncid,'PRES_DY','valid_max',6000)
% ncwriteatt(ncid,'PRES_DY','coordinates','TIME DEPTH LATITUDE LONGITUDE')
% ncwriteatt(ncid,'PRES_DY','QC_indicator','Good data')
% ncwriteatt(ncid,'PRES_DY','Processing_level','Data manually reviewed')
% ncwriteatt(ncid,'PRES_DY','ancillary_variables','PRES_QC')
% ncwriteatt(ncid,'PRES_DY','sensor_mount','mounted_on_mooring_line')
% ncwriteatt(ncid,'PRES_DY','sensor_name','SBE37S')
% ncwriteatt(ncid,'PRES_DY','sensor_serial_number',inputs.serial_pressure)
% 
% ncwriteatt(ncid,'PRES_DY_QC','long_name','quality flag')
% ncwriteatt(ncid,'PRES_DY_QC','conventions','OceanSITES reference table 2')
% ncwriteatt(ncid,'PRES_DY_QC','valid_min',0)
% ncwriteatt(ncid,'PRES_DY_QC','valid_max',5)
% %ncwriteatt(ncid,'PRES_DY_QC','valid_max',9)
% ncwriteatt(ncid,'PRES_DY_QC','flag_values',int8([0,1,2,3,4,5]))
% %ncwriteatt(ncid,'PRES_DY_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
% ncwriteatt(ncid,'PRES_DY_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
% %ncwriteatt(ncid,'PRES_DY_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')
% 
% ncwriteatt(ncid,'CNDC_DY','long_name','sea water conductivity')
% ncwriteatt(ncid,'CNDC_DY','standard_name','sea_water_electrical_conductivity')
% ncwriteatt(ncid,'CNDC_DY','units','S/m')
% ncwriteatt(ncid,'CNDC_DY','valid_min',0)
% ncwriteatt(ncid,'CNDC_DY','valid_max',7)
% ncwriteatt(ncid,'CNDC_DY','coordinates','TIME DEPTH LATITUDE LONGITUDE')
% ncwriteatt(ncid,'CNDC_DY','QC_indicator','Good data')
% ncwriteatt(ncid,'CNDC_DY','Processing_level','Data manually reviewed')
% ncwriteatt(ncid,'CNDC_DY','ancillary_variables','CNDC_DY_QC')
% ncwriteatt(ncid,'CNDC_DY','sensor_mount','mounted_on_mooring_line')
% ncwriteatt(ncid,'CNDC_DY','sensor_name','SBE37S')
% ncwriteatt(ncid,'CNDC_DY','sensor_serial_number',inputs.serial)
% 
% ncwriteatt(ncid,'CNDC_DY_QC','long_name','quality flag')
% ncwriteatt(ncid,'CNDC_DY_QC','conventions','OceanSITES reference table 2')
% ncwriteatt(ncid,'CNDC_DY_QC','valid_min',0)
% ncwriteatt(ncid,'CNDC_DY_QC','valid_max',5)
% %ncwriteatt(ncid,'CNDC_DY_QC','valid_max',9)
% ncwriteatt(ncid,'CNDC_DY_QC','flag_values',int8([0,1,2,3,4,5]))
% %ncwriteatt(ncid,'CNDC_DY_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
% ncwriteatt(ncid,'CNDC_DY_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
% %ncwriteatt(ncid,'CNDC_DY_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')
%
% if strcmp(inputs.mooring(1:2),'pa')
%   ncwriteatt(ncid,'DENS_DY','long_name','sigma-theta (potential density adjusted to 4000m)')
% elseif strcmp(inputs.mooring(1:2),'ke')
%   ncwriteatt(ncid,'DENS_DY','long_name','sigma-theta (potential density adjusted to 6000m)')
% end
% ncwriteatt(ncid,'DENS_DY','standard_name','sea_water_sigma_theta')
% ncwriteatt(ncid,'DENS_DY','units','kg m-3')
% ncwriteatt(ncid,'DENS_DY','valid_min',0)
% ncwriteatt(ncid,'DENS_DY','valid_max',50)
% ncwriteatt(ncid,'DENS_DY','coordinates','TIME DEPTH LATITUDE LONGITUDE')
% ncwriteatt(ncid,'DENS_DY','QC_indicator','Good data')
% ncwriteatt(ncid,'DENS_DY','Processing_level','Data manually reviewed')
% ncwriteatt(ncid,'DENS_DY','ancillary_variables','DENS_DY_QC')
% ncwriteatt(ncid,'DENS_DY','sensor_mount','mounted_on_mooring_line')
% ncwriteatt(ncid,'DENS_DY','sensor_name','SBE37S')
% ncwriteatt(ncid,'DENS_DY','sensor_serial_number',inputs.serial)
% ncwriteatt(ncid,'DENS_DY','comment','Derived from measured conductivity, temperature, and pressure.')
% 
% ncwriteatt(ncid,'DENS_DY_QC','long_name','quality flag')
% ncwriteatt(ncid,'DENS_DY_QC','conventions','OceanSITES reference table 2')
% ncwriteatt(ncid,'DENS_DY_QC','valid_min',0)
% ncwriteatt(ncid,'DENS_DY_QC','valid_max',5)
% %ncwriteatt(ncid,'DENS_DY_QC','valid_max',9)
% ncwriteatt(ncid,'DENS_DY_QC','flag_values',int8([0,1,2,3,4,5]))
% %ncwriteatt(ncid,'DENS_DY_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
% ncwriteatt(ncid,'DENS_DY_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
% %ncwriteatt(ncid,'DENS_DY_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')
% 
% ncwriteatt(ncid,'PSAL_DY','long_name','sea water salinity')
% ncwriteatt(ncid,'PSAL_DY','standard_name','sea_water_practical_salinity')
% ncwriteatt(ncid,'PSAL_DY','units','1')
% ncwriteatt(ncid,'PSAL_DY','valid_min',25)
% ncwriteatt(ncid,'PSAL_DY','valid_max',45)
% ncwriteatt(ncid,'PSAL_DY','coordinates','TIME DEPTH LATITUDE LONGITUDE')
% ncwriteatt(ncid,'PSAL_DY','QC_indicator','Good data')
% ncwriteatt(ncid,'PSAL_DY','Processing_level','Data manually reviewed')
% ncwriteatt(ncid,'PSAL_DY','ancillary_variables','PSAL_DY_QC')
% ncwriteatt(ncid,'PSAL_DY','reference_scale','PSS-78')
% ncwriteatt(ncid,'PSAL_DY','sensor_mount','mounted_on_mooring_line')
% ncwriteatt(ncid,'PSAL_DY','sensor_name','SBE37S')
% ncwriteatt(ncid,'PSAL_DY','sensor_serial_number',inputs.serial)
% ncwriteatt(ncid,'PSAL_DY','comment','Derived from measured conductivity, temperature, and pressure.')
% 
% ncwriteatt(ncid,'PSAL_DY_QC','long_name','quality flag')
% ncwriteatt(ncid,'PSAL_DY_QC','conventions','OceanSITES reference table 2')
% ncwriteatt(ncid,'PSAL_DY_QC','valid_min',0)
% ncwriteatt(ncid,'PSAL_DY_QC','valid_max',5)
% %ncwriteatt(ncid,'PSAL_DY_QC','valid_max',9)
% ncwriteatt(ncid,'PSAL_DY_QC','flag_values',int8([0,1,2,3,4,5]))
% %ncwriteatt(ncid,'PSAL_DY_QC','flag_values',int8([0,1,2,3,4,7,8,9]))
% ncwriteatt(ncid,'PSAL_DY_QC','flag_meanings','datum_missing highest_quality default_quality adjusted_data lower_quality sensor_failed')
% %ncwriteatt(ncid,'PSAL_DY_QC','flag_meanings','unknown good_data probably_good_data bad_data_that_are_potentially_correctable bad_data nominal_value interpolated_value missing_value')



% Add global attributes
ncwriteatt(ncid1,'/','data_type','OceanSITES time-series data')
%ncwriteatt(ncid1,'/','data_type','DisDel time-series data')
ncwriteatt(ncid1,'/','format_version','1.3')
ncwriteatt(ncid1,'/','date_created',datestr(now,'yyyy-mm-ddTHH:MM:ssZ'))
ncwriteatt(ncid1,'/','date_modified',datestr(now,'yyyy-mm-ddTHH:MM:ssZ'))
ncwriteatt(ncid1,'/','institution','NOAA/Pacific Marine Environmental Laboratory')
ncwriteatt(ncid1,'/','project','Ocean Climate Stations (OCS)')
ncwriteatt(ncid1,'/','network','OCS')
ncwriteatt(ncid1,'/','wmo_platform_code',platcode)
ncwriteatt(ncid1,'/','source','Moored surface buoy')
ncwriteatt(ncid1,'/','history',sprintf('%s %s',datestr(now,'yyyy-mm-ddTHH:MM:ssZ'),'data updated at PMEL'))
ncwriteatt(ncid1,'/','data_mode','D')
ncwriteatt(ncid1,'/','QC_indicator','excellent')
ncwriteatt(ncid1,'/','processing_level','Ranges applied, bad data flagged')
ncwriteatt(ncid1,'/','references','http://www.oceansites.org, http://www.pmel.noaa.gov/OCS/')
ncwriteatt(ncid1,'/','comment',sprintf('To conform to surrounding time-series, Temperatures and Conductivities were adjusted by %+g degrees C and %+g mS/cm, respectively. These offsets are less than or equal to the instrument error.',inputs.adjtemp,inputs.adjcond))
ncwriteatt(ncid1,'/','Conventions','OceanSITES Manual 1.3, CF-1.6')
ncwriteatt(ncid1,'/','netcdf_version',netcdf.inqLibVers)
ncwriteatt(ncid1,'/','naming_authority','OceanSITES')
ncwriteatt(ncid1,'/','id',ncid1(1:end-3))
ncwriteatt(ncid1,'/','cdm_data_type','Station')
ncwriteatt(ncid1,'/','time_coverage_start',datestr(double(time(1)),'yyyy-mm-ddTHH:MM:ssZ'))
ncwriteatt(ncid1,'/','time_coverage_end',datestr(double(time(end)),'yyyy-mm-ddTHH:MM:ssZ'))
ncwriteatt(ncid1,'/','institution_references','http://www.pmel.noaa.gov/')
ncwriteatt(ncid1,'/','contact','OCS Data Manager: ocs@noaa.gov')
ncwriteatt(ncid1,'/','publisher_name','Nathan Anderson')
ncwriteatt(ncid1,'/','publisher_email','nathan.anderson@noaa.gov')
ncwriteatt(ncid1,'/','publisher_url','http://www.pmel.noaa.gov/ocs/people')
ncwriteatt(ncid1,'/','data_assembly_center','PMEL')
ncwriteatt(ncid1,'/','principal_investigator','Dr. Meghan F. Cronin')
ncwriteatt(ncid1,'/','principal_investigator_email','meghan.f.cronin@noaa.gov')
ncwriteatt(ncid1,'/','principal_investigator_url','http://www.pmel.noaa.gov/people/cronin')
ncwriteatt(ncid1,'/','license','These data are made freely available without restriction')
ncwriteatt(ncid1,'/','citation','These data were collected and made freely available by the OceanSITES project and the Ocean Climate Stations (OCS) Project Office of NOAA/PMEL')
ncwriteatt(ncid1,'/','update_interval','void')
ncwriteatt(ncid1,'/','qc_manual','http://www.oceansites.org/docs/oceansites_data_format_reference_manual.pdf')
ncwriteatt(ncid1,'/','Data_Source','OCS Project Office/NOAA/PMEL')
ncwriteatt(ncid1,'/','acknowledgement',['If you use these data in publications of presentations, please acknowledge the OCS Project Office ', ...
'of NOAA/PMEL.  Also, we would appreciate receiving a preprint and/or reprint of publications utilizing the data for inclusion in our bibliography.  ', ...
'Relevant publications should be sent to: OCS Project Office, NOAA/PMEL/OCRD, 7600 Sand Point Way NE, Seattle, WA 98115 or emailed to: meghan.f.cronin@noaa.gov'])
ncwriteatt(ncid1,'/','platform_code',location)
ncwriteatt(ncid1,'/','site_code',location)
ncwriteatt(ncid1,'/','array',array)
ncwriteatt(ncid1,'/','title',sprintf('OceanSITES Station %s In-Situ %s Resolution Data',location,'10-Minute'))
ncwriteatt(ncid1,'/','geospatial_lon_min',sprintf('%.2f',lons(1)))
ncwriteatt(ncid1,'/','geospatial_lon_max',sprintf('%.2f',lons(2)))
ncwriteatt(ncid1,'/','geospatial_lat_min',sprintf('%.2f',lats(1)))
ncwriteatt(ncid1,'/','geospatial_lat_max',sprintf('%.2f',lats(2)))
ncwriteatt(ncid1,'/','area',area)
ncwriteatt(ncid1,'/','geospatial_vertical_min',sprintf('%.0f',floor(sal.pressure2depth(min(dft.pres),lat))))
ncwriteatt(ncid1,'/','geospatial_vertical_max',sprintf('%.0f',ceil(sal.pressure2depth(max(dft.pres),lat))))
ncwriteatt(ncid1,'/','geospatial_vertical_positive','down')
ncwriteatt(ncid1,'/','summary',sprintf('This file contains high resolution delayed-mode in-situ data from the deep SBE instrument on the OceanSITES Station %s %s %s (%s) deployment.',location,nomloc,datestr(double(time(1)),'yyyy'),upper(inputs.mooring)))


ncwriteatt(ncid2,'/','data_type','OceanSITES time-series data')
%ncwriteatt(ncid2,'/','data_type','DisDel time-series data')
ncwriteatt(ncid2,'/','format_version','1.3')
ncwriteatt(ncid2,'/','date_created',datestr(now,'yyyy-mm-ddTHH:MM:ssZ'))
ncwriteatt(ncid2,'/','date_modified',datestr(now,'yyyy-mm-ddTHH:MM:ssZ'))
ncwriteatt(ncid2,'/','institution','NOAA/Pacific Marine Environmental Laboratory')
ncwriteatt(ncid2,'/','project','Ocean Climate Stations (OCS)')
ncwriteatt(ncid2,'/','network','OCS')
ncwriteatt(ncid2,'/','wmo_platform_code',platcode)
ncwriteatt(ncid2,'/','source','Moored surface buoy')
ncwriteatt(ncid2,'/','history',sprintf('%s %s',datestr(now,'yyyy-mm-ddTHH:MM:ssZ'),'data updated at PMEL'))
ncwriteatt(ncid2,'/','data_mode','D')
ncwriteatt(ncid2,'/','QC_indicator','excellent')
ncwriteatt(ncid2,'/','processing_level','Ranges applied, bad data flagged')
ncwriteatt(ncid2,'/','references','http://www.oceansites.org, http://www.pmel.noaa.gov/OCS/')
ncwriteatt(ncid2,'/','comment',sprintf('To conform to surrounding time-series, Temperatures and Conductivities were adjusted by %+g degrees C and %+g mS/cm, respectively. These offsets are less than or equal to the instrument error.',inputs.adjtemp,inputs.adjcond))
ncwriteatt(ncid2,'/','Conventions','OceanSITES Manual 1.3, CF-1.6')
ncwriteatt(ncid2,'/','netcdf_version',netcdf.inqLibVers)
ncwriteatt(ncid2,'/','naming_authority','OceanSITES')
ncwriteatt(ncid2,'/','id',ncid2(1:end-3))
ncwriteatt(ncid2,'/','cdm_data_type','Station')
ncwriteatt(ncid2,'/','time_coverage_start',datestr(double(time_hr(1)),'yyyy-mm-ddTHH:MM:ssZ'))
ncwriteatt(ncid2,'/','time_coverage_end',datestr(double(time_hr(end)),'yyyy-mm-ddTHH:MM:ssZ'))
ncwriteatt(ncid2,'/','institution_references','http://www.pmel.noaa.gov/')
ncwriteatt(ncid2,'/','contact','OCS Data Manager: ocs@noaa.gov')
ncwriteatt(ncid2,'/','publisher_name','Nathan Anderson')
ncwriteatt(ncid2,'/','publisher_email','nathan.anderson@noaa.gov')
ncwriteatt(ncid2,'/','publisher_url','http://www.pmel.noaa.gov/ocs/people')
ncwriteatt(ncid2,'/','data_assembly_center','PMEL')
ncwriteatt(ncid2,'/','principal_investigator','Dr. Meghan F. Cronin')
ncwriteatt(ncid2,'/','principal_investigator_email','meghan.f.cronin@noaa.gov')
ncwriteatt(ncid2,'/','principal_investigator_url','http://www.pmel.noaa.gov/people/cronin')
ncwriteatt(ncid2,'/','license','These data are made freely available without restriction')
ncwriteatt(ncid2,'/','citation','These data were collected and made freely available by the OceanSITES project and the Ocean Climate Stations (OCS) Project Office of NOAA/PMEL')
ncwriteatt(ncid2,'/','update_interval','void')
ncwriteatt(ncid2,'/','qc_manual','http://www.oceansites.org/docs/oceansites_data_format_reference_manual.pdf')
ncwriteatt(ncid2,'/','Data_Source','OCS Project Office/NOAA/PMEL')
ncwriteatt(ncid2,'/','acknowledgement',['If you use these data in publications of presentations, please acknowledge the OCS Project Office ', ...
'of NOAA/PMEL.  Also, we would appreciate receiving a preprint and/or reprint of publications utilizing the data for inclusion in our bibliography.  ', ...
'Relevant publications should be sent to: OCS Project Office, NOAA/PMEL/OCRD, 7600 Sand Point Way NE, Seattle, WA 98115 or emailed to: meghan.f.cronin@noaa.gov'])
ncwriteatt(ncid2,'/','platform_code',location)
ncwriteatt(ncid2,'/','site_code',location)
ncwriteatt(ncid2,'/','array',array)
ncwriteatt(ncid2,'/','title',sprintf('OceanSITES Station %s In-Situ %s Resolution Data',location,'Hourly'))
ncwriteatt(ncid2,'/','geospatial_lon_min',sprintf('%.2f',lons(1)))
ncwriteatt(ncid2,'/','geospatial_lon_max',sprintf('%.2f',lons(2)))
ncwriteatt(ncid2,'/','geospatial_lat_min',sprintf('%.2f',lats(1)))
ncwriteatt(ncid2,'/','geospatial_lat_max',sprintf('%.2f',lats(2)))
ncwriteatt(ncid2,'/','area',area)
ncwriteatt(ncid2,'/','geospatial_vertical_min',sprintf('%.0f',floor(sal.pressure2depth(min(flt.pres),lat))))
ncwriteatt(ncid2,'/','geospatial_vertical_max',sprintf('%.0f',ceil(sal.pressure2depth(max(flt.pres),lat))))
ncwriteatt(ncid2,'/','geospatial_vertical_positive','down')
ncwriteatt(ncid2,'/','summary',sprintf('This file contains hourly resolution delayed-mode in-situ data from the deep SBE instrument on the OceanSITES Station %s %s %s (%s) deployment.',location,nomloc,datestr(double(time(1)),'yyyy'),upper(inputs.mooring)))

end

