function [ MissingGlobals, FoundGlobals ] = checkOSglobals (nc_file)
% checkOSglobals 2021/07/15 Nan Galbraith
% check an OceanSITES netcdf file and report back the missing (and found) 
% global attributes, based on an in-line table taken from OceanSITES 
% Data Format Reference Manual V 1.4,  at 
% oceansites.org/docs/oceansites_data_format_reference_manual.pdf
%
%% INPUT: 
% nc_file: name (including path) to the file to be checked
%
%% RETURNS:
%  MissingGlobals: a cell array containing the names of global attributes 
%     that are required/recommended by DFRM v 1.4
%  FoundGlobals: a structure that contains the names AND values of the 
%     globals that are required/recommended and found in the file.
%
%% Implementation note: 
% Any additional global attributes that are NOT required/recommented are
% ignored; these extra attributes are allowed under the OceanSITES spec

info=ncinfo(nc_file);

% OceanSITES global attributes (cell)
OSglobals={  'site_code'; 'platform_code'; 'data_mode'; ...
    'title'; 'theme'; 'summary'; 'naming_authority'; 'id'; ...
    'wmo_platform_code'; 'source'; 'principal_investigator'; ...
    'principal_investigator_email'; 'principal_investigator_url'; ...
    'principal_investigator_id'; 'creator_name'; 'creator_email'; ...
    'creator_url'; 'creator_id'; 'creator_type'; 'creator_institution'; ...
    'array'; 'network'; 'keywords_vocabulary'; 'keywords'; 'comment'; ...
    'sea_area'; 'geospatial_lat_min'; 'geospatial_lat_max'; ...
    'geospatial_lat_units'; 'geospatial_lon_min'; 'geospatial_lon_max'; ...
    'geospatial_lon_units'; 'geospatial_vertical_min'; ...
    'geospatial_vertical_max'; 'geospatial_vertical_positive'; ...
    'geospatial_vertical_units'; 'time_coverage_start'; 'time_coverage_end';...
    'time_coverage_duration'; 'time_coverage_resolution'; 'cdm_data_type'; ...
    'featureType'; 'platform_deployment_date'; 'platform_deployment_ship_name'; ...
    'platform_deployment_cruise_name'; 'platform_deployment_ship_ICES_code'; ...
    'platform_deployment_cruise_ExpoCode'; 'platform_recovery_date'; ...
    'platform_recovery_ship_name'; 'platform_recovery_cruise_name'; ...
    'platform_recovery_ship_ICES_code'; 'platform_recovery_cruise_ExpoCode';...
    'data_type'; 'format_version'; 'Conventions'; 'netcdf_version'; ...
    'publisher_name'; 'publisher_email'; 'publisher_url'; 'publisher_ID';...
    'references'; 'data_assembly_center'; 'update_interval'; 'license';...
    'citation'; 'acknowledgement'; 'date_created'; 'date_modified';...
    'history'; 'processing_level'; 'QC_indicator'; 'contributor_name';...
    'contributor_role'; 'contributor_email'};

nmissing=0;
MissingGlobals={[1,length(OSglobals)]}; % empty cell array
FoundGlobals = struct;  % empty struct
for gg=1:length(OSglobals)
    gname=char(OSglobals{gg});
    fprintf('%s\t',gname);
    found=0;
    for ff=1:length(info.Attributes)
        if strcmpi(gname, info.Attributes(ff).Name)
            fprintf( ' -- found');
            found=1; 
            eval(['FoundGlobals.' gname ' = info.Attributes(ff).Value;']);
        end
    end
    if found
        fprintf('\n');
%         nfound=nfound+1;
%         FoundGlobals{nfound}=gname;
    else
        fprintf(' -- MISSING!\n');
        nmissing=nmissing+1;
        MissingGlobals{nmissing}=gname;
    end
end

